version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
    - /workspaces/ensf400-lab9-jenkins/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    # build using the dockerfile
    build: .
    ports:
      #accessible on port 8888 
      - "8888:8080"
    container_name: my-ensf-java-app

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true