// This jenkinsfile is used to run CI/CD on my local (Windows) box, no VM's needed.

pipeline {

  agent any

   environment {
        // This is set so that the Python API tests will recognize it
        // and go through the Zap proxy waiting at 9888
        HTTP_PROXY = 'http://127.0.0.1:9888'
   }

  stages {

    // build the war file (the binary).  This is the only
    // place that happens.
    stage('Build') {
      steps {
          // go to demo-master to find the gradle file
          dir('demo-master') {
            sh 'chmod +x ./gradlew'
            sh './gradlew clean assemble'
          }
      }
    }

    // run all the unit tests - these do not require anything else
    // to be running and most run very quickly.
    stage('Unit Tests') {
      steps {
        dir('demo-master') {
          sh './gradlew test'
        }
      }
      post {
        always {
          dir('demo-master') {
            junit 'build/test-results/test/*.xml'
          }
        }
      }
    }

    // run the tests which require connection to a
    // running database.
    stage('Database Tests') {
      steps {
        dir('demo-master') {
          sh './gradlew integrate'
        }
      }
      post {
        always {
          dir('demo-master') {
            junit 'build/test-results/integrate/*.xml'
          }
        }
      }
    }

    // These are the Behavior Driven Development (BDD) tests
    // See the files in src/bdd_test
    // These tests do not require a running system.
    stage('BDD Tests') {
      steps {
        dir('demo-master') {
          sh './gradlew generateCucumberReports'
          // generate the code coverage report for jacoco
          sh './gradlew jacocoTestReport'
        }
      }
      post {
          always {
            dir('demo-master') {
              junit 'build/test-results/bdd/*.xml'
            }
          }
        }
    }

    // // Runs an analysis of the code, looking for any
    // // patterns that suggest potential bugs.
    stage('Static Analysis') {
      steps {
        dir('demo-master') {
          // sh './gradlew sonarqube'
          // // wait for sonarqube to finish its analysis
          // sleep 5
          // sh './gradlew checkQualityGate'
          sh './gradlew sonarqube -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login="admin" -Dsonar.password="ensf400"'

        }
      }
    }
  }
}