name: Build Docker image
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  # Job is named build-image
  build-image:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Extract commit SHA
        run: | 
          echo branch: ${{ github.ref_name }} 
          echo hash $(git rev-parse --short HEAD)
